"""Compatibility shim — implementation moved to services.multi_runtime.schemas."""

from __future__ import annotations

from services.multi_runtime.schemas import (
    AssistantAttachRequest,
    AssistantAttachResponse,
    AudioMetadata,
    Capabilities,
    ContentItem,
    DaemonConfigRequest,
    DaemonConfigResponse,
    DaemonParamsInfo,
    DaemonStatusResponse,
    FallbackResponse,
    GenerationConfig,
    HealthResponse,
    MessageItem,
    ModelInfo,
    RespondRequest,
    RespondResponse,
    RestartResponse,
    SoftReloadResponse,
    StatusResponse,
    TranscribeRequest,
    TranscribeResponse,
    VRAMStatus,
)

__all__ = [
    "AssistantAttachRequest",
    "AssistantAttachResponse",
    "AudioMetadata",
    "Capabilities",
    "ContentItem",
    "DaemonConfigRequest",
    "DaemonConfigResponse",
    "DaemonParamsInfo",
    "DaemonStatusResponse",
    "FallbackResponse",
    "GenerationConfig",
    "HealthResponse",
    "MessageItem",
    "ModelInfo",
    "RespondRequest",
    "RespondResponse",
    "RestartResponse",
    "SoftReloadResponse",
    "StatusResponse",
    "TranscribeRequest",
    "TranscribeResponse",
    "VRAMStatus",
]
