name: venom-minimal

# Security policy (MVP):
# This profile is intended for trusted/private networks only.
# Services are published on host interfaces to allow testing from another machine in LAN.
services:
  ollama:
    image: ${OLLAMA_IMAGE:-ollama/ollama:latest}
    container_name: venom-ollama-minimal
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      # Avoid curl/wget dependency: ollama image may not include them.
      test: ["CMD", "ollama", "list"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 20s
    restart: unless-stopped

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: venom-backend-minimal
    environment:
      ENV: production
      URL_SCHEME_POLICY: ${URL_SCHEME_POLICY:-auto}
      AI_MODE: LOCAL
      ACTIVE_LLM_SERVER: ollama
      LLM_SERVICE_TYPE: local
      LLM_LOCAL_ENDPOINT: ${LLM_HTTP_SCHEME:-http}://ollama:11434/v1
      LLM_MODEL_NAME: ${OLLAMA_MODEL:-gemma3:4b}
      SUMMARY_STRATEGY: heuristic_only
    depends_on:
      ollama:
        # Do not hard-block startup on healthcheck here.
        # Health is verified explicitly by installer/CI via HTTP checks.
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - venom-data:/app/data
      - venom-workspace:/app/workspace
      - venom-logs:/app/logs
    healthcheck:
      # Liveness check: keep it independent from optional subsystems.
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 15s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: venom-frontend-minimal
    environment:
      NEXT_PUBLIC_ENV: ${ENV:-production}
      URL_SCHEME_POLICY: ${URL_SCHEME_POLICY:-auto}
      NEXT_PUBLIC_URL_SCHEME_POLICY: ${URL_SCHEME_POLICY:-auto}
      API_PROXY_TARGET: ${HTTP_SCHEME:-http}://backend:8000
      NEXT_PUBLIC_API_BASE: ${HTTP_SCHEME:-http}://localhost:8000
      NEXT_PUBLIC_WS_BASE: ${WS_SCHEME:-ws}://localhost:8000/ws/events
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 15s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  ollama-data:
  venom-data:
  venom-workspace:
  venom-logs:
