# =============================================================================
# Makefile maps and operator help
# =============================================================================

help:
	@echo "Venom Makefile - najczęściej używane komendy"
	@echo ""
	@echo "Start/Stop (dev):"
	@echo "  make start                    - start backend + frontend (webpack-safe dev) + runtime LLM"
	@echo "  make start-lowmem             - start backend + frontend (low-memory, no local LLM runtime)"
	@echo "  make stop                     - stop backend + frontend + runtime LLM"
	@echo "  make status                   - status procesów"
	@echo "  make web-dev                  - frontend dev (webpack, fallback)"
	@echo "  make web-dev-turbo            - frontend dev (turbopack, opt-in)"
	@echo "  make web-dev-turbo-debug      - frontend dev turbopack + debug logi"
	@echo ""
	@echo "Testy:"
	@echo "  make test                     - backend testy (clean artifacts)"
	@echo "  make test-data                - backend testy (preserve artifacts)"
	@echo "  make test-web-unit            - frontend unit"
	@echo "  make test-web-e2e             - frontend e2e"
	@echo "  make test-web-turbo-smoke     - smoke dev:turbo"
	@echo "  make test-web-turbo-smoke-clean - smoke dev:turbo + clean .next"
	@echo ""
	@echo "Preprod:"
	@echo "  make start-preprod            - start stacka preprod (readonly profile)"
	@echo "  make preprod-backup           - backup danych preprod"
	@echo "  make preprod-verify TS=...    - verify + smoke readonly po backupie"
	@echo "  make preprod-readiness-check  - check gotowości preprod"
	@echo ""
	@echo "Runtime LLM:"
	@echo "  make vllm-start|stop|restart  - kontrola usługi vLLM"
	@echo "  make ollama-start|stop|restart - kontrola usługi Ollama"
	@echo "  make multi-runtime-start|stop|restart|hygiene - kontrola usługi Multi-Runtime"
	@echo "  make local-first-help          - mapa operatora local-first"
	@echo ""
	@echo "Jakość:"
	@echo "  make pr-fast                  - hard gate (wymagane przed zakończeniem)"
	@echo "  make make-targets-audit       - audyt .PHONY vs zdefiniowane targety"
	@echo "  make chat-operator-docs-drift-audit - audit docs/operator help drift"
	@echo "  make operator-manual-docs-drift-audit - audit operator manual drift"
	@echo "  make the-chat-docs-drift-audit - audit THE_CHAT overview drift"
	@echo "  make audit-dead-code          - heurystyczny audyt ślepego kodu (Python)"
	@echo "  make audit-dead-code-vulture-install - ręczna instalacja vulture do .venv"
	@echo "  make audit-dead-code-full     - dead-code audit + sygnał vulture (soft)"
	@echo "  make stack-stability-audit    - ręczny audyt stabilności procesów web/API + portów + manifestów modułów"
	@echo "  make llm-runtime-stability-audit - ręczny audyt lifecycle runtime/model (ollama/vllm/onnx) na aktywnym backendzie"
	@echo "  make llm-runtime-stability-cycle-start - cykl: make start -> audit runtime -> make stop"
	@echo "  make llm-runtime-stability-cycle-start2 - cykl: make start2 -> audit runtime -> make stop"
	@echo "  make test-groups-check        - weryfikacja grup testów"
	@echo "  make test-catalog-check       - weryfikacja katalogu testów"

local-first-help:
	@echo "Venom local-first - mapa operatora"
	@echo ""
	@echo "Lifecycle:"
	@echo "  make local-first-start MODEL=qwen2.5-coder:7b   - start Ollama + preload modelu"
	@echo "  make local-first-status                          - status Ollama/Codex + modele"
	@echo "  make local-repo-status                           - lokalny stan repo (git), bez LLM/API"
	@echo "  make local-repo-status-json                      - lokalny stan repo jako JSON, bez LLM/API"
	@echo "  make local-first-codex MODEL=... [PROMPT='...']  - uruchom Codex local (Ollama)"
	@echo "  make local-first-repo-truth-agent MODEL=...      - lane repo-truth-first"
	@echo "  make local-first-pr240-orchestrator-routing-probe - kontrakt subagent routing dla repo-truth"
	@echo "  make local-first-pr240-full-agent-handoff-probe   - kontrakt handoff glownego agenta do orchestratora"
	@echo "  make local-first-unload MODEL=...               - unload wybranego modelu"
	@echo "  make local-first-unload-all                      - unload wszystkich aktywnych modeli"
	@echo "  make local-first-stop                            - zatrzymanie usługi Ollama"
	@echo ""
	@echo "Diagnostics:"
	@echo "  make local-first-feedback-probe                  - benchmark modeli pod analizę feedbacku"
	@echo "  make local-first-tool-flake-probe                - matrix flake tool-call"
	@echo "  make local-first-operator-tool-profile-probe     - operator core/extended profile"
	@echo "  make local-first-chat-diagnostics                - truth/tool matrix lokalnego chatu"
	@echo "  make local-first-copilot-chat-output-probe       - wykrywanie raw tool-call JSON w odpowiedzi asystenta"
	@echo "  make local-first-copilot-agent-session-probe     - kontrakt sesji/modelu Agent dla stabilnego tool-loop"
	@echo "  make local-first-copilot-chat-output-gate        - diagnostics + enforce clean assistant output"
	@echo "  make local-first-local-agent-tool-loop-probe     - health check local-agent-first (qwen + realny tool-loop)"
	@echo "  make local-first-local-agent-tool-loop-gate      - gate local-agent-first: tool-loop + clean output"
	@echo "  make local-first-vscode-agent-log-probe LOG_FILE=... - probe exportu Agent Debug Log pod evidence tool-loop"
	@echo "  make local-first-vscode-terminal-tool-loop-probe - kontrakt auto-approve terminala dla bezpiecznych komend git"
	@echo "  make local-first-local-model-tool-call-probe     - czy model lokalny zwraca structured tool_calls"
	@echo "  make local-first-pr239-selftest                  - automatyczny test diagnostyczny PR239 (bez manualnego testera)"
	@echo "  make local-first-pr242-as-is                     - PR242 AS-IS routing matrix snapshot"
	@echo "  make local-first-pr242-command-loop-probe        - PR242 command-execution loop probe"
	@echo "  make local-first-pr242-native-chat-probe         - PR242 native chat probe"
	@echo "  make local-first-pr242-vscode-executor-test      - PR242 VSCode executor probe (bez IDE)"
	@echo "  make local-first-pr242-routing-matrix            - PR242 full helper matrix"
	@echo "  make local-first-pr242-gate                      - PR242 aggregate helper gate"
	@echo "  make local-first-git-status                      - execution lane: dokładny git status --short --branch"
	@echo "  make local-first-repo-truth-reply                - dokladny status git + deterministic counts"
	@echo "  make local-first-chat-tool-bridge PAYLOAD_FILE=...   - wykonaj lokalnie tool-call JSON i zwroc wynik + analize"
	@echo "  make local-first-repo-truth-preflight-probe      - twardy preflight repo-truth"
	@echo "  make local-first-env-index-readiness-probe       - readiness env/index"
	@echo "  make local-first-agent-decision-evidence-probe   - evidence schema repo-truth-first"
	@echo "  make local-first-agent-state-registry-probe      - canonical agent state registry snapshot"
	@echo "  make local-first-policy-enforcement-probe        - repo-truth policy gate"
	@echo "  make local-first-decision-gate                   - final operator/utility model routing gate"
	@echo "  make local-first-agent-decision-gate             - final gate env/index + evidence + state registry"
	@echo "  make local-first-agent-config-validate           - walidacja konfiguracji agentow"
	@echo "  make local-first-vscode-agent-probe              - kontrakt terminala VSCODE_AGENT"
	@echo "  make local-first-utility-models-probe            - kontrakt utility modeli czatu"
	@echo "  make local-first-workspace-context-probe         - kontrakt workspace context"
	@echo ""
	@echo "Full agent:"
	@echo "  make local-first-full-agent-contract-probe       - kontrakt pelnego agenta"
	@echo "  make local-first-full-agent-debug-probe          - debug loop pelnego agenta"
	@echo "  make local-first-full-agent-handoff-probe        - handoff implementation"
	@echo "  make local-first-full-agent-tool-probe           - tool-loop pelnego agenta"
	@echo "  make local-first-full-agent-gate                 - final gate pelnego agenta"
	@echo ""
	@echo "Profile:"
	@echo "  make local-first-profile-status                  - status profilu local-first w shellu"
	@echo "  make local-first-profile-print                   - wypisz aktualny fragment profilu"
	@echo "  make local-first-profile-install                 - zainstaluj profile hooks do shella"
	@echo "  make local-first-profile-remove                  - usun profile hooks z shella"
	@echo "  make local-first-profile-backup"
	@echo "  make local-first-profile-list-backups"
	@echo "  make local-first-profile-restore [RESTORE_FILE=...]"
